FROM debian:bookworm

RUN apt update
RUN apt install -y curl unzip git make procps python3 python3-pip python3.11-venv jq gh

WORKDIR /usr/local/src/tron

COPY . .

RUN curl -L https://foundry.paradigm.xyz | bash
RUN chmod a+x install-forge.sh

RUN ./install-forge.sh --with-build

CMD ["./install-forge.sh", "--with-deploy"]

#CMD ["tail", "-f", "/dev/null"]
