FROM debian:bookworm

RUN apt update
RUN apt install -y curl git make procps python3 python3-pip python3.11-venv

WORKDIR /usr/local/src/tron

COPY . .

RUN curl -L https://foundry.paradigm.xyz | bash
RUN chmod a+x install-forge.sh

CMD ["./install-forge.sh --with-deploy"]
