FROM debian:bullseye

RUN apt update
RUN apt install -y curl git make procps python3 python3-pip

WORKDIR /usr/local/src/delylah

COPY . .

RUN curl -L https://foundry.paradigm.xyz | bash
RUN chmod a+x install-forge.sh

#CMD ["./install-forge.sh"]
CMD ["tail", "-f", "/dev/null"]