#!/bin/bash

function parseContractAddress() {
    ADDRESS_UNCUT=$(jq 'nth('$3'; .transactions[] | select((.transactionType=="CREATE") and (.contractName=="'$1'"))) | .contractAddress' broadcast/ApplicationDeployAll.s.sol/$2/run-latest.json)
    ADDRESS="${ADDRESS_UNCUT//\"}"
    echo $ADDRESS
}

ENV_FILE=".env"

CHAIN_ID=31337
settingChainID=false

  for var in "$@"
  do
    if [[ "$var" = "--chainid" ]]
    then
      settingChainID=true
    elif $settingChainID;
    then
      CHAIN_ID="$var"
      settingVal=false
    elif [[ "$var" = "--help" ]]
    then
      echo "--------------------------------------------------"
      echo "Possible Arguments:"
      echo "--chainid - set the chain id for the deployment"
      echo "--------------------------------------------------"
      exit
    else
      echo "Unknown Argument"
    fi
  done

echo

# Retreive the App Manager
APPLICATION_APP_MANAGER=$(parseContractAddress "ApplicationAppManager" $CHAIN_ID 0)
echo APPLICATION_APP_MANAGER=$APPLICATION_APP_MANAGER
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_APP_MANAGER=.*/TEST_DEPLOY_APPLICATION_APP_MANAGER='$APPLICATION_APP_MANAGER'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_APP_MANAGER=.*/TEST_DEPLOY_APPLICATION_APP_MANAGER='$APPLICATION_APP_MANAGER'/g' $ENV_FILE 
fi

# Retrieve the App Handler
APPLICATION_APPLICATION_HANDLER=$(parseContractAddress "ApplicationHandler" $CHAIN_ID 0)
echo APPLICATION_APPLICATION_HANDLER=$APPLICATION_APPLICATION_HANDLER
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_APPLICATION_HANDLER=.*/TEST_DEPLOY_APPLICATION_APPLICATION_HANDLER='$APPLICATION_APPLICATION_HANDLER'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_APPLICATION_HANDLER=.*/TEST_DEPLOY_APPLICATION_APPLICATION_HANDLER='$APPLICATION_APPLICATION_HANDLER'/g' $ENV_FILE
fi

# Retrieve the ERC 20
APPLICATION_ERC20_ADDRESS=$(parseContractAddress "ApplicationERC20" $CHAIN_ID 0)
echo APPLICATION_ERC20_ADDRESS=$APPLICATION_ERC20_ADDRESS
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS='$APPLICATION_ERC20_ADDRESS'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS='$APPLICATION_ERC20_ADDRESS'/g' $ENV_FILE
fi

# Retrieve the ERC 20 Handler
APPLICATION_ERC20_HANDLER_ADDRESS=$(parseContractAddress "HandlerDiamond" $CHAIN_ID 0)
echo APPLICATION_ERC20_HANDLER_ADDRESS=$APPLICATION_ERC20_HANDLER_ADDRESS
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS='$APPLICATION_ERC20_HANDLER_ADDRESS'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS='$APPLICATION_ERC20_HANDLER_ADDRESS'/g' $ENV_FILE 
fi

# Retrieve the ERC 20
APPLICATION_ERC20_ADDRESS_2=$(parseContractAddress "ApplicationERC20" $CHAIN_ID 1)
echo APPLICATION_ERC20_ADDRESS=$APPLICATION_ERC20_ADDRESS_2
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS_2=.*/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS_2='$APPLICATION_ERC20_ADDRESS_2'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS_2=.*/TEST_DEPLOY_APPLICATION_ERC20_ADDRESS_2='$APPLICATION_ERC20_ADDRESS_2'/g' $ENV_FILE 
fi

# Retrieve the Oracle Allowed Contract Address 
APPLICATION_ORACLE_ALLOWED_ADDRESS=$(parseContractAddress "OracleApproved" $CHAIN_ID 0)
echo APPLICATION_ORACLE_ALLOWED_ADDRESS=$APPLICATION_ORACLE_ALLOWED_ADDRESS
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ORACLE_ALLOWED_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ORACLE_ALLOWED_ADDRESS='$APPLICATION_ORACLE_ALLOWED_ADDRESS'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ORACLE_ALLOWED_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ORACLE_ALLOWED_ADDRESS='$APPLICATION_ORACLE_ALLOWED_ADDRESS'/g' $ENV_FILE
fi



# Retrieve the Oracle Denied Contract Address 
APPLICATION_ORACLE_DENIED_ADDRESS=$(parseContractAddress "OracleDenied" $CHAIN_ID 0)
echo APPLICATION_ORACLE_DENIED_ADDRESS=$APPLICATION_ORACLE_DENIED_ADDRESS
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ORACLE_DENIED_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ORACLE_DENIED_ADDRESS='$APPLICATION_ORACLE_DENIED_ADDRESS'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ORACLE_DENIED_ADDRESS=.*/TEST_DEPLOY_APPLICATION_ORACLE_DENIED_ADDRESS='$APPLICATION_ORACLE_DENIED_ADDRESS'/g' $ENV_FILE 
fi

# Retrieve the ERC 721 
APPLICATION_ERC721_ADDRESS_1=$(parseContractAddress "ApplicationERC721AdminOrOwnerMint" $CHAIN_ID 0)
echo APPLICATION_ERC721_ADDRESS_1=$APPLICATION_ERC721_ADDRESS_1
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ERC721_ADDRESS_1=.*/TEST_DEPLOY_APPLICATION_ERC721_ADDRESS_1='$APPLICATION_ERC721_ADDRESS_1'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ERC721_ADDRESS_1=.*/TEST_DEPLOY_APPLICATION_ERC721_ADDRESS_1='$APPLICATION_ERC721_ADDRESS_1'/g' $ENV_FILE
fi

# Retrieve the ERC 721 Handler
APPLICATION_ERC721_HANDLER=$(parseContractAddress "HandlerDiamond" $CHAIN_ID 2)
echo APPLICATION_ERC721_HANDLER=$APPLICATION_ERC721_HANDLER
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ERC721_HANDLER=.*/TEST_DEPLOY_APPLICATION_ERC721_HANDLER='$APPLICATION_ERC721_HANDLER'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ERC721_HANDLER=.*/TEST_DEPLOY_APPLICATION_ERC721_HANDLER='$APPLICATION_ERC721_HANDLER'/g' $ENV_FILE 
fi

# Retrieve the ERC 721 Pricing
ERC721_PRICING_CONTRACT=$(parseContractAddress "ApplicationERC721Pricing" $CHAIN_ID 0)
echo ERC721_PRICING_CONTRACT=$ERC721_PRICING_CONTRACT
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_ERC721_PRICING_CONTRACT=.*/TEST_DEPLOY_ERC721_PRICING_CONTRACT='$ERC721_PRICING_CONTRACT'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_ERC721_PRICING_CONTRACT=.*/TEST_DEPLOY_ERC721_PRICING_CONTRACT='$ERC721_PRICING_CONTRACT'/g' $ENV_FILE
fi

# Retrieve the ERC 20 Pricing
ERC20_PRICING_CONTRACT=$(parseContractAddress "ApplicationERC20Pricing" $CHAIN_ID 0)
echo ERC20_PRICING_CONTRACT=$ERC20_PRICING_CONTRACT
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_ERC20_PRICING_CONTRACT=.*/TEST_DEPLOY_ERC20_PRICING_CONTRACT='$ERC20_PRICING_CONTRACT'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_ERC20_PRICING_CONTRACT=.*/TEST_DEPLOY_ERC20_PRICING_CONTRACT='$ERC20_PRICING_CONTRACT'/g' $ENV_FILE 
fi

# Retreive the Second App Manager
APPLICATION_APP_MANAGER_2=$(parseContractAddress "ApplicationAppManager" $CHAIN_ID 1)
echo APPLICATION_APP_MANAGER_2=$APPLICATION_APP_MANAGER_2
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_APP_MANAGER_2=.*/TEST_DEPLOY_APPLICATION_APP_MANAGER_2='$APPLICATION_APP_MANAGER_2'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_APP_MANAGER_2=.*/TEST_DEPLOY_APPLICATION_APP_MANAGER_2='$APPLICATION_APP_MANAGER_2'/g' $ENV_FILE 
fi

# Retrieve the ERC 20 Handler
APPLICATION_ERC20_HANDLER_ADDRESS_2=$(parseContractAddress "HandlerDiamond" $CHAIN_ID 1)
echo APPLICATION_ERC20_HANDLER_ADDRESS_2=$APPLICATION_ERC20_HANDLER_ADDRESS_2
echo

os=$(uname -a)
if [[ $os == *"Darwin"* ]]; then
  sed -i '' 's/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS_2=.*/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS_2='$APPLICATION_ERC20_HANDLER_ADDRESS_2'/g' $ENV_FILE
else
  sed -i 's/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS_2=.*/TEST_DEPLOY_APPLICATION_ERC20_HANDLER_ADDRESS_2='$APPLICATION_ERC20_HANDLER_ADDRESS_2'/g' $ENV_FILE 
fi

