name: Test

on:
  push:
    branches:
      - main
      - internal
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Build and Test Invariants
    runs-on: ubuntu-latest-m-16

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Increase swapfile
          # https://github.com/actions/runner-images/discussions/7188#discussioncomment-6750749
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # June 2, 2024 - Must be a release (nightly) tag
          version: nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559

      - name: Install dependencies
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install eth_abi
          forge install dapphub/ds-test 
          forge install OpenZeppelin/openzeppelin-contracts
      - name: Build
        run: |
          forge clean && forge build --optimize
      - name: Test
        run: |
          forge test -vv --ffi --un --match-tests invariant
